# Generated by Django 4.0.2 on 2022-03-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='created',
        ),
    ]
