# Generated by Django 4.0.2 on 2022-03-03 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tasklist_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='due',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 0, 29, 21, 6446)),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 0, 29, 21, 6446)),
        ),
    ]
